### ISSUE TITLE
`@zzzen/pyright-internal` didn't update recently

### ISSUE THREAD

**Issue by fannheyward** [Zzzen/pyright-packager#1]
Hello, the `@zzzen/pyright-internal` package didn't update recently, is there anything wrong with the npm publish? https://github.com/Zzzen/pyright-packager/blob/main/.github/workflows/npm-publish.yml

**Comment by Zzzen** [comment]
>![image](https://user-images.githubusercontent.com/6630042/203994990-e7fb00c6-1119-43df-a338-98d8cfe76079.png)

Thanks for reporting this problem! I've enabled it manually and am considering using [keepalive-workflow](https://github.com/marketplace/actions/keepalive-workflow) to bypass it.

**Comment by fannheyward** [comment]
@Zzzen sorry to boring you, but the publish action failed to build recently.

**Comment by Zzzen** [comment]
Thanks for reporting the issue! It has been fixed now.

**Comment by fannheyward** [comment]
@Zzzen sorry to boring you again, the publish actions failed with `npm ci`.

**Comment by Zzzen** [comment]
Resolved. Thanks for letting me know!
